name: Foundation CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Test Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: sudo apt-get update && sudo apt-get install -y build-essential libsodium-dev libboost-system-dev
      - run: npm install
        env:
          CXXFLAGS: "-std=c++17"
      - run: npm test
  coverage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Save Coverage Checks
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: sudo apt-get update && sudo apt-get install -y build-essential libsodium-dev libboost-system-dev
      - run: npm install
        env:
          CXXFLAGS: "-std=c++17"
      - run: npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
